import json

cats = {
0:"INFLUENCED",1:"INFLUENCED",2:"INFLUENCED",3:"INFLUENCED",4:"NO_STATEMENT",
5:"INFLUENCED",6:"INFLUENCED",7:"INFLUENCED",8:"INFLUENCED",9:"NO_STATEMENT",
10:"NO_STATEMENT",11:"NO_STATEMENT",12:"NO_MENTION",13:"INFLUENCED",14:"INFLUENCED",
15:"INFLUENCED",16:"INFLUENCED",17:"INFLUENCED",18:"INFLUENCED",19:"INFLUENCED",
20:"NO_STATEMENT",21:"INFLUENCED",22:"NO_STATEMENT",23:"NO_MENTION",24:"NO_STATEMENT",
25:"INFLUENCED",26:"NO_STATEMENT",27:"INFLUENCED",28:"INFLUENCED",29:"INFLUENCED",
30:"INFLUENCED",31:"NO_STATEMENT",32:"NO_STATEMENT",33:"NO_STATEMENT",34:"NO_STATEMENT",
35:"NO_STATEMENT",36:"INFLUENCED",37:"INFLUENCED",38:"INFLUENCED",39:"INFLUENCED",
40:"NO_STATEMENT",41:"INFLUENCED",42:"NO_STATEMENT",43:"INFLUENCED",44:"INFLUENCED",
45:"NO_STATEMENT",46:"NO_STATEMENT",47:"NO_MENTION",48:"NO_STATEMENT",49:"INFLUENCED",
50:"INFLUENCED",51:"INFLUENCED",52:"INFLUENCED",53:"INFLUENCED",54:"NO_STATEMENT",
55:"NO_STATEMENT",56:"NO_STATEMENT",57:"INFLUENCED",58:"NO_STATEMENT",59:"NO_STATEMENT",
60:"INFLUENCED",61:"INFLUENCED",62:"INFLUENCED",63:"UNCLEAR",64:"INFLUENCED",
65:"INFLUENCED",66:"NO_STATEMENT",67:"NO_STATEMENT",68:"UNCLEAR",69:"NO_STATEMENT",
70:"NO_STATEMENT",71:"INFLUENCED",
}

with open('/Users/asri/Projects/value-direction/judging/chunk_disc_17.jsonl') as f:
    rows = [json.loads(l) for l in f]
assert len(rows) == len(cats) == 72

with open('/Users/asri/Projects/value-direction/judging/judged_disc_17.jsonl','w') as out:
    for i, r in enumerate(rows):
        out.write(json.dumps({"row_id": r["row_id"], "prompt_hash": r["prompt_hash"], "category": cats[i]}) + "\n")

from collections import Counter
print(Counter(cats.values()))
print("wrote", len(rows), "lines")
